# Generated by Django 5.1.7 on 2025-03-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
