# Generated by Django 5.1.7 on 2025-03-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0002_perfil_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
