# Generated by Django 5.1.7 on 2025-03-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0005_publicacion_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechaPublicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
