# Generated by Django 5.1.7 on 2025-03-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0006_alter_publicacion_fechapublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(upload_to='fotos_perfil/'),
        ),
    ]
