# Generated by Django 5.1.7 on 2025-03-20 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0008_perfil_amigos_alter_publicacion_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='amigos',
            field=models.ManyToManyField(blank=True, related_name='mis_amigos', to=settings.AUTH_USER_MODEL),
        ),
    ]
