# Generated by Django 5.1.7 on 2025-03-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0009_alter_perfil_amigos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='user',
            new_name='autor',
        ),
    ]
