# Generated by Django 5.1.7 on 2025-03-21 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0010_rename_user_publicacion_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redsocialapp.perfil'),
        ),
    ]
