# Generated by Django 5.1.7 on 2025-04-03 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0014_comentario_cantidadcomentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='cantidadComentarios',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='cantidadComentarios',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
