# Generated by Django 5.1.7 on 2025-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0015_remove_comentario_cantidadcomentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
