# Generated by Django 5.1.7 on 2025-04-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0019_alter_perfil_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
