# Generated by Django 5.2 on 2025-04-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0020_perfil_codigo_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='creado',
            field=models.BooleanField(default=False),
        ),
    ]
