# Generated by Django 5.2 on 2025-04-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0023_novedades_publicacion_novedades_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedades',
            old_name='publicacion',
            new_name='post',
        ),
    ]
