# Generated by Django 5.2 on 2025-04-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0024_rename_publicacion_novedades_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='token_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
