# Generated by Django 5.2 on 2025-05-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0026_alter_comentario_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='comentario',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
