# Generated by Django 5.2 on 2025-05-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0027_novedades_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='leida',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
