# Generated by Django 5.2 on 2025-11-18 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocialapp', '0029_alter_publicacion_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='amigos',
        ),
        migrations.AddField(
            model_name='novedades',
            name='aceptada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='tipo',
            field=models.CharField(choices=[('like', 'Me gusta'), ('comentario', 'Comentario'), ('amigo', 'Solicitud de amistad'), ('sistema', 'Sistema')], default='sistema', max_length=20),
        ),
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('solicitante', 'receptor')},
            },
        ),
    ]
